name: Node CI

on:
    push:
        branches: ["**"]
    pull_request:
        branches: [master]

jobs:
    extension_tests:
        name: Extensions tests
        env:
            CI: true
        strategy:
            matrix:
                node-version: [12.x]
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Lint source
              run: |
                  npm run ci:all
                  npm run eslint-check
            - name: Run prettier if not Windows
              if: matrix.os != 'windows-latest'
              run: npm run prettier-check
            - name: Run tests
              uses: GabrielBB/xvfb-action@v1.0
              with:
                  run: npm test

    build_and_upload:
        name: Build and upload
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master' || startsWith( github.ref, 'refs/tags/v' )
        needs: [extension_tests]
        runs-on: [ubuntu-latest]
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Build E2E images
              run: docker build -f ./containers/ubuntu-test/Dockerfile . -t tmc-vscode-ubuntu-test
            - name: Run ui tests
              run: docker run -t --rm tmc-vscode-ubuntu-test
            - name: Package extension
              run: |
                  npm install -g vsce
                  vsce package
                  # move packaged extension from project root to own release folder
                  mkdir extension && mv *.vsix extension
              env:
                  CI: true
            - name: Upload artifact
              uses: actions/upload-artifact@v1
              if: success()
              with:
                  name: packaged-extension
                  path: extension/
            - name: Publish if ${{ github.ref }} is a tag
              if: success() && startsWith( github.ref, 'refs/tags/v' )
              run: |
                  chmod +x bin/validateRelease.sh
                  bin/validateRelease.sh ${{ github.ref }}
                  vsce publish -p ${{ secrets.VSCE_PUBLISH_TOKEN }} --packagePath extension/*.vsix
