
name: Node CI

on: [push, pull_request]

jobs:
  test_and_build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run tests
      run: |
        npm ci
        npm run compile
        npm run tslint
        # use xvfb to render into virtual framebuffer
        sudo apt-get install xvfb
        xvfb-run --auto-servernum npm test
      env:
        CI: true
    - name: upload artifact
      if: success()
      run: |
        npm install -g vsce
        vsce package
        # move packaged extension from root to own release folder
        mkdir extension && mv *.vsix extension
    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: packaged-extension
        path: extension/
