name: Node CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm ci
        npm run compile --if-present
        sudo apt-get install xvfb
        xvfb-run --auto-servernum npm test
      env:
        CI: true

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install package and upload artifact
      run: |
        npm install -g vsce
        npm install
        vsce package
        mkdir extension && mv *.vsix extension
      env:
        CI: true
    - uses: actions/upload-artifact@v1
      with:
        name: packaged-extension
        path: extension/
