name: Extension tests

on: push

jobs:
    extension_tests:
        name: Extensions tests
        env:
            CI: true
        strategy:
            matrix:
                node-version: [12.x]
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Lint source
              run: |
                  npm run ci:all
                  npm run eslint-check
            - name: Run prettier if not Windows
              if: matrix.os != 'windows-latest'
              run: npm run prettier-check
            - name: Setup backend
              run: |
                  cd backend
                  npm run setup
                  chmod -R +x resources
                  cd ..
            - name: Run tests
              uses: GabrielBB/xvfb-action@v1.0
              with:
                  run: npm test
