
name: Release

#on:
#  create:
#    ref_type: 'tag'

# Temp check pushes instead of having to create tags
on:
  push:
    branches:
      tag-release

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Validate release
      run: |
        chmod +x bin/validateRelease.sh
        # Temp simulated pass / ${{ github.ref }}
        bin/validateRelease.sh refs/tags/v0.1.2
